services:
  db:
    image: postgres:14-alpine
    container_name: course_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Монтируем скрипт инициализации
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DATABASE_NAME}"]  # Исправленный healthcheck
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - course-network

  app:
    build: .
    container_name: course_bot
    depends_on:
      db:
        condition: service_healthy
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - ADMIN_CHAT_ID=${ADMIN_CHAT_ID}
      - BOT_MODE=${BOT_MODE}
      - DB_NAME=${DATABASE_NAME}
      - DB_USER=${APP_DB_USER}
      - DB_PASSWORD=${APP_DB_PASSWORD}
      - DB_HOST=db
      - DB_PORT=5432
      - NODE_ENV=production
      - RUN_STANDALONE=true
    volumes:
      - ./videos:/app/videos
    restart: unless-stopped
    networks:
      - course-network

volumes:
  postgres_data:

networks:
  course-network:
    driver: bridge